// Generated by gencpp from file rosplan_knowledge_msgs/GetDomainNameServiceResponse.msg
// DO NOT EDIT!


#ifndef ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETDOMAINNAMESERVICERESPONSE_H
#define ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETDOMAINNAMESERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplan_knowledge_msgs
{
template <class ContainerAllocator>
struct GetDomainNameServiceResponse_
{
  typedef GetDomainNameServiceResponse_<ContainerAllocator> Type;

  GetDomainNameServiceResponse_()
    : domain_name()  {
    }
  GetDomainNameServiceResponse_(const ContainerAllocator& _alloc)
    : domain_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _domain_name_type;
  _domain_name_type domain_name;





  typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetDomainNameServiceResponse_

typedef ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<std::allocator<void> > GetDomainNameServiceResponse;

typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse > GetDomainNameServiceResponsePtr;
typedef boost::shared_ptr< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse const> GetDomainNameServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator1> & lhs, const ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.domain_name == rhs.domain_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator1> & lhs, const ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_knowledge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60174b39a7780212f0384c8d050df5a0";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60174b39a7780212ULL;
  static const uint64_t static_value2 = 0xf0384c8d050df5a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_knowledge_msgs/GetDomainNameServiceResponse";
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string domain_name\n"
"\n"
;
  }

  static const char* value(const ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.domain_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDomainNameServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_knowledge_msgs::GetDomainNameServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "domain_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.domain_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_KNOWLEDGE_MSGS_MESSAGE_GETDOMAINNAMESERVICERESPONSE_H
