// Generated by gencpp from file rosplan_dispatch_msgs/ParsingServiceRequest.msg
// DO NOT EDIT!


#ifndef ROSPLAN_DISPATCH_MSGS_MESSAGE_PARSINGSERVICEREQUEST_H
#define ROSPLAN_DISPATCH_MSGS_MESSAGE_PARSINGSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplan_dispatch_msgs
{
template <class ContainerAllocator>
struct ParsingServiceRequest_
{
  typedef ParsingServiceRequest_<ContainerAllocator> Type;

  ParsingServiceRequest_()
    : plan_path()  {
    }
  ParsingServiceRequest_(const ContainerAllocator& _alloc)
    : plan_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _plan_path_type;
  _plan_path_type plan_path;





  typedef boost::shared_ptr< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ParsingServiceRequest_

typedef ::rosplan_dispatch_msgs::ParsingServiceRequest_<std::allocator<void> > ParsingServiceRequest;

typedef boost::shared_ptr< ::rosplan_dispatch_msgs::ParsingServiceRequest > ParsingServiceRequestPtr;
typedef boost::shared_ptr< ::rosplan_dispatch_msgs::ParsingServiceRequest const> ParsingServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator1> & lhs, const ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.plan_path == rhs.plan_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator1> & lhs, const ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_dispatch_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c771004eab052df9a3c0b81e4de4eddd";
  }

  static const char* value(const ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc771004eab052df9ULL;
  static const uint64_t static_value2 = 0xa3c0b81e4de4edddULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_dispatch_msgs/ParsingServiceRequest";
  }

  static const char* value(const ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# parses a plan from a file\n"
"string plan_path\n"
;
  }

  static const char* value(const ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParsingServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_dispatch_msgs::ParsingServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "plan_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.plan_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_DISPATCH_MSGS_MESSAGE_PARSINGSERVICEREQUEST_H
