// Generated by gencpp from file rosplan_dispatch_msgs/PlanningServiceResponse.msg
// DO NOT EDIT!


#ifndef ROSPLAN_DISPATCH_MSGS_MESSAGE_PLANNINGSERVICERESPONSE_H
#define ROSPLAN_DISPATCH_MSGS_MESSAGE_PLANNINGSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosplan_dispatch_msgs
{
template <class ContainerAllocator>
struct PlanningServiceResponse_
{
  typedef PlanningServiceResponse_<ContainerAllocator> Type;

  PlanningServiceResponse_()
    : plan_found(false)  {
    }
  PlanningServiceResponse_(const ContainerAllocator& _alloc)
    : plan_found(false)  {
  (void)_alloc;
    }



   typedef uint8_t _plan_found_type;
  _plan_found_type plan_found;





  typedef boost::shared_ptr< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlanningServiceResponse_

typedef ::rosplan_dispatch_msgs::PlanningServiceResponse_<std::allocator<void> > PlanningServiceResponse;

typedef boost::shared_ptr< ::rosplan_dispatch_msgs::PlanningServiceResponse > PlanningServiceResponsePtr;
typedef boost::shared_ptr< ::rosplan_dispatch_msgs::PlanningServiceResponse const> PlanningServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator1> & lhs, const ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.plan_found == rhs.plan_found;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator1> & lhs, const ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosplan_dispatch_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6541069453c664f560eb34e369510c16";
  }

  static const char* value(const ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6541069453c664f5ULL;
  static const uint64_t static_value2 = 0x60eb34e369510c16ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosplan_dispatch_msgs/PlanningServiceResponse";
  }

  static const char* value(const ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool plan_found\n"
"\n"
;
  }

  static const char* value(const ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan_found);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanningServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosplan_dispatch_msgs::PlanningServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "plan_found: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plan_found);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPLAN_DISPATCH_MSGS_MESSAGE_PLANNINGSERVICERESPONSE_H
