// Generated by gencpp from file chat_client/Num.msg
// DO NOT EDIT!


#ifndef CHAT_CLIENT_MESSAGE_NUM_H
#define CHAT_CLIENT_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chat_client
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : pub()
    , str()  {
    }
  Num_(const ContainerAllocator& _alloc)
    : pub(_alloc)
    , str(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _pub_type;
  _pub_type pub;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _str_type;
  _str_type str;





  typedef boost::shared_ptr< ::chat_client::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chat_client::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::chat_client::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::chat_client::Num > NumPtr;
typedef boost::shared_ptr< ::chat_client::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chat_client::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chat_client::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chat_client::Num_<ContainerAllocator1> & lhs, const ::chat_client::Num_<ContainerAllocator2> & rhs)
{
  return lhs.pub == rhs.pub &&
    lhs.str == rhs.str;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chat_client::Num_<ContainerAllocator1> & lhs, const ::chat_client::Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chat_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chat_client::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chat_client::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chat_client::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chat_client::Num_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chat_client::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chat_client::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chat_client::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaf759e25d19bdc5a284d26603fbb1c8";
  }

  static const char* value(const ::chat_client::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaf759e25d19bdc5ULL;
  static const uint64_t static_value2 = 0xa284d26603fbb1c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::chat_client::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chat_client/Num";
  }

  static const char* value(const ::chat_client::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chat_client::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string pub\n"
"string str\n"
;
  }

  static const char* value(const ::chat_client::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chat_client::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pub);
      stream.next(m.str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chat_client::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chat_client::Num_<ContainerAllocator>& v)
  {
    s << indent << "pub: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pub);
    s << indent << "str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHAT_CLIENT_MESSAGE_NUM_H
